### ISSUE TITLE
Query for CMU_Mocap Output Generated

### ISSUE THREAD

**Issue by Dipankar1997161** [Iridoudou/Pose_to_SMPL#2]
Hello @Dou-Yiming,

I wanted to fit the CMU_Mocap dataset, 

I did the following: doanload the dataset and set the path in the config files and then run the command:
**(smplpytorch) [ndip@dst-jyk Pose_to_SMPL]$ python fit/tools/main.py --exp cmu --dataset_name CMU_Mocap --dataset_path /mnt/data/ndip/mocap/mocap_3djoints/**

(smplpytorch) [ndip@dst-jyk Pose_to_SMPL]$ python fit/tools/main.py  --exp cmu --dataset_name CMU_Mocap --dataset_path /mnt/data/ndip/mocap/mocap_3djoints/
2023-05-23 14:40:23,060 - __main__ - INFO - Start print log
2023-05-23 14:40:23,060 - __main__ - INFO - using device: cpu
2023-05-23 14:40:23,248 - __main__ - INFO - Fitting finished! Average loss:     0.000000000

**NO output(SMPL Parameters) were generated for the command except:**

![Screenshot 2023-05-23 140504](https://github.com/Dou-Yiming/Pose_to_SMPL/assets/85514219/6b94eea8-bb2f-4ee9-bc51-da7376acb624)

Here is how my JSON looks like for CMU_Mocap
![Screenshot 2023-05-23 140646](https://github.com/Dou-Yiming/Pose_to_SMPL/assets/85514219/4246453a-3d67-4d9a-bc08-1de5033593ae)

### I guess I did some mistake, could you please tell me. Do let me know as I wish to do the same for all the datasets

**Comment by Dipankar1997161** [comment]
Solved. Thank you

**Comment by TT-T1** [comment]
Hello, I encountered the same situation as you during my experiment, and I don't quite understand what this result means and how to use it. Could you help me explain it?
